version: "3"
services:
  bot:
    build: .
    volumes:
      - /usr/src/app/node_modules
    restart: always
    ports:
      - "80:3000"
    command: ["./wait-for-it.sh", "mysql:3306", "--", "db/first_run.sh"]

  mysql:
    container_name: mariadb
    restart: always
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'down_and_dirty_deeds'
      MYSQL_USER: 'max_attack'
      MYSQL_PASS: 'headroom_dead_batteries'
      MYSQL_DATABASE: 'max'
    volumes:
      - my-datavolume:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  my-datavolume:
