version: "3"
services:
  bot:
    build: .
    volumes:
      - /usr/src/app/node_modules
    restart: always
    ports:
      - "$BOT_PORT_HOST:$BOT_PORT_GUEST"
    command: ["./wait-for-it.sh", "mysql:3306", "--", "db/first_run.sh"]

  mysql:
    container_name: mariadb
    restart: always
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASS: $MYSQL_PASS
      MYSQL_DATABASE: $MYSQL_DATABASE
    volumes:
      - my-datavolume:/var/lib/mysql
    ports:
      - "$DB_PORT_HOST:$DB_PORT_GUEST"
volumes:
  my-datavolume: {}
